[
  { quality: "common", value: 2, weigh: "18", percent: "18" },
  { quality: "common", value: 3, weigh: "14", percent: "14" },
  { quality: "common", value: 4, weigh: "44", percent: "44" },
  { quality: "common", value: 5, weigh: "12", percent: "12" },
  { quality: "common", value: 6, weigh: "8", percent: "8" },
  { quality: "common", value: 7, weigh: "4", percent: "4" },
  { quality: "uncommon", value: 4, weigh: "30", percent: "30" },
  { quality: "uncommon", value: 5, weigh: "22", percent: "22" },
  { quality: "uncommon", value: 6, weigh: "15", percent: "15" },
  { quality: "uncommon", value: 7, weigh: "10", percent: "10" },
  { quality: "uncommon", value: 8, weigh: "8", percent: "8" },
  { quality: "uncommon", value: 9, weigh: "6", percent: "6" },
  { quality: "uncommon", value: 10, weigh: "4", percent: "4" },
  { quality: "uncommon", value: 11, weigh: "3", percent: "3" },
  { quality: "uncommon", value: 12, weigh: "2", percent: "2" },
];
